Feature reservation
RafaelBahiense/Drivent-Back pull request #6
Opened 2021-09-08 14:59 UTC by mateusrfon

2021-09-09 16:37 UTC, RafaelBahiense approved these changes

2021-09-09 20:45 UTC, gugabs requested changes
Resolver conflitos

2021-09-09 20:45 UTC, gugabs commented on .prettierrc.json
> +>>>>>>> main
Remover os resquícios de conflitos do git.

2021-09-10 01:44 UTC, mateusrfon commented on .prettierrc.json
> +>>>>>>> main
Pronto! Resolvi e realizei alguns ajustes necessários.

2021-09-10 18:01 UTC, gugabs requested changes
Complemento dos testes. (Foi realizado no próximo PR)

2021-09-10 18:01 UTC, gugabs commented on tests/integration/reservation.test.ts
> +  });
Além desse, estão faltando os casos de teste das outras rotas de `/reservation` como os GET's e o outro POST.

2021-09-10 18:02 UTC, gugabs approved these changes

2021-09-10 18:44 UTC, merged